version: 2.1

jobs:
  build:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: |
          npm install
          npm build
  publish:
    docker:
      - image: docker
    steps:
      - checkout
      - run: |
          docker build -t alexbsd/nodejs-sample-app .
          docker push alexbsd/nodejs-sample-app
    
workflows:
  my-custom-workflow:
    jobs:
      - build
      - publish