version: 2.1
orbs:
  docker: circleci/docker@1.7.0
workflows:
    example-workflow:
      jobs:
        - docker/publish:
            docker-username: DOCKER_LOGIN 
            docker-password: DOCKER_PASSWORD 
            image: nodejs-sample-app 