version: 2.1

jobs:
  build:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: |
          npm install
          npm build
  publish:
    machine:
      image: ubuntu-2004:202107-02
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          docker build -t alexbsd/nodejs-sample-app .
          docker push alexbsd/nodejs-sample-app
workflows:
  version: 2
  custom_workflow:
    jobs:
      - build
      - publish:
          requires:
            - build